### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by IbrahimShamma99** [lujakob/nestjs-realworld-example-app#31]
```
> nestjs-realworld-example-app@1.0.0 start /home/ibrahim/Repos/nestjs-realworld-example-app
> node index.js

[Nest] 13547   - 01/31/2020, 1:08 PM   [NestFactory] Starting Nest application...
[Nest] 13547   - 01/31/2020, 1:08 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +42ms
Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/home/ibrahim/Repos/nestjs-realworld-example-app/src/connection/ConnectionOptionsReader.ts:41:19)
    at step (/home/ibrahim/Repos/nestjs-realworld-example-app/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/ibrahim/Repos/nestjs-realworld-example-app/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/ibrahim/Repos/nestjs-realworld-example-app/node_modules/tslib/tslib.js:104:62)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Nest] 13547   - 01/31/2020, 1:08 PM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
```

**Comment by caiopiassali** [comment]
Rename `ormconfig.json.example` to `ormconfig.json`.

**Comment by lujakob** [comment]
The error message is straight forward: "Unable to connect to the database." - did you rename the ormconfig.json.example as mentioned in the readme. Did you alter the DB config to your DB?
